version: '3.8'

services:
    app:
        build: .
        image: openjdk:17-jdk-slim
        container_name: springboot-app
        working_dir: /app
        volumes:
            - ./target:/app
        command: ["java", "-jar", "Ecommerce-Monolito-0.0.1-SNAPSHOT.jar"]
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: ecommerce-db
        environment:
            POSTGRES_DB: ecommerce_db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - ecommerce_data:/var/lib/postgresql/data

volumes:
    ecommerce_data: